"""
config_gui.py — Bulk-configure your news-remotion project from a GUI.

Edits src/config.ts (which every component reads from) so you can change
channel name, background video, color palette, and image scale without
touching any code.

Drop next to news_images.py in D:\\news\\.  The GUI defaults to looking for
the Remotion project at .\\news-remotion next to the script.

What it does on Apply:
  1. Validates every field (paths exist, colors are valid hex, scale in range).
  2. If you picked a new background-video file from outside public/, copies
     it to public/<basename>.
  3. Regenerates news-remotion/src/config.ts.
  4. Logs everything to the right-side panel.

You can reuse the GUI for bulk work — change channel name / colors / video,
hit Apply, render that video in Remotion Studio, change config again for
the next video, hit Apply, render, etc. Every Apply is non-destructive
except for the config.ts overwrite.
"""

import re
import shutil
from pathlib import Path

import tkinter as tk
from tkinter import ttk, filedialog, colorchooser, messagebox, scrolledtext


# ============================================================
# Config schema
# ============================================================
DEFAULT_CONFIG = {
    "channelName": "The News Report",
    "channelTagline": "Daily Briefing",
    "useBackgroundVideo": True,
    "backgroundVideo": "background.mp4",
    "imageScale": 0.70,
    "colors": {
        "accent": "#c8a464",
        "cream": "#f4f1e8",
        "dark": "#0a0a0c",
        "paper": "#f5f1e8",
    },
}

CONFIG_TS_TEMPLATE = """\
/**
 * News Remotion configuration.
 *
 * Auto-generated by config_gui.py. Edit values via the GUI, or directly
 * here — but be aware the GUI overwrites this file on its next "Apply".
 */
export const CONFIG = {{
  // -------- Channel branding (top-left during image scenes) --------
  channelName: "{channelName}",
  channelTagline: "{channelTagline}",

  // -------- Background video (image scenes only) --------
  useBackgroundVideo: {useBackgroundVideo},
  backgroundVideo: "{backgroundVideo}",

  // How much of the 1920x1080 frame the news image card occupies.
  // Safe range: 0.65 to 0.78.
  imageScale: {imageScale:.2f},

  // -------- Color palette --------
  colors: {{
    accent: "{accent}",
    cream: "{cream}",
    dark: "{dark}",
    paper: "{paper}",
  }},
}};

export type AppConfig = typeof CONFIG;
"""


# ============================================================
# Config file I/O
# ============================================================
def parse_config_ts(path: Path) -> dict:
    """Best-effort parse of a config.ts that was generated by this script.
    Falls back to defaults for any field that's missing or unparseable.
    """
    result = {
        "channelName": DEFAULT_CONFIG["channelName"],
        "channelTagline": DEFAULT_CONFIG["channelTagline"],
        "useBackgroundVideo": DEFAULT_CONFIG["useBackgroundVideo"],
        "backgroundVideo": DEFAULT_CONFIG["backgroundVideo"],
        "imageScale": DEFAULT_CONFIG["imageScale"],
        "colors": dict(DEFAULT_CONFIG["colors"]),
    }
    if not path.exists():
        return result

    text = path.read_text(encoding="utf-8")

    def find_str(key, default):
        m = re.search(rf'{key}\s*:\s*"([^"]*)"', text)
        return m.group(1) if m else default

    def find_bool(key, default):
        m = re.search(rf"{key}\s*:\s*(true|false)", text)
        if m:
            return m.group(1) == "true"
        return default

    def find_num(key, default):
        m = re.search(rf"{key}\s*:\s*([\d.]+)", text)
        try:
            return float(m.group(1)) if m else default
        except ValueError:
            return default

    result["channelName"] = find_str("channelName", result["channelName"])
    result["channelTagline"] = find_str("channelTagline", result["channelTagline"])
    result["useBackgroundVideo"] = find_bool("useBackgroundVideo", result["useBackgroundVideo"])
    result["backgroundVideo"] = find_str("backgroundVideo", result["backgroundVideo"])
    result["imageScale"] = find_num("imageScale", result["imageScale"])
    for k in result["colors"]:
        result["colors"][k] = find_str(k, result["colors"][k])
    return result


def write_config_ts(path: Path, cfg: dict) -> None:
    payload = {
        "channelName": cfg["channelName"].replace('"', '\\"'),
        "channelTagline": cfg["channelTagline"].replace('"', '\\"'),
        "useBackgroundVideo": "true" if cfg["useBackgroundVideo"] else "false",
        "backgroundVideo": cfg["backgroundVideo"],
        "imageScale": float(cfg["imageScale"]),
        **cfg["colors"],
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(CONFIG_TS_TEMPLATE.format(**payload), encoding="utf-8")


# ============================================================
# GUI
# ============================================================
HEX_RE = re.compile(r"^#[0-9a-fA-F]{6}$")


class ConfigGUI:
    def __init__(self, root: tk.Tk):
        self.root = root
        self.root.title("News Remotion — Bulk Config")
        self.root.geometry("1200x780")
        self.root.configure(padx=10, pady=10)

        # ---- Tk variables ----
        script_dir = Path(__file__).parent.resolve()
        default_project = script_dir / "news-remotion"

        self.project_path = tk.StringVar(value=str(default_project))
        self.channel_name = tk.StringVar()
        self.channel_tagline = tk.StringVar()
        self.use_bg_video = tk.BooleanVar()
        # `bg_video_path` holds either an absolute path (newly chosen file) or
        # just a filename (loaded from existing config — assumed already in public/).
        self.bg_video_path = tk.StringVar()
        self.image_scale = tk.DoubleVar()
        self.color_vars = {
            "accent": tk.StringVar(),
            "cream": tk.StringVar(),
            "dark": tk.StringVar(),
            "paper": tk.StringVar(),
        }
        self.color_swatches = {}  # widget refs

        # ---- Layout: left form, right log ----
        paned = tk.PanedWindow(root, orient=tk.HORIZONTAL, sashwidth=8, bg="#ccc")
        paned.pack(fill=tk.BOTH, expand=True)

        self.left = tk.Frame(paned, padx=10, pady=10)
        self._build_form()
        paned.add(self.left, minsize=620)

        self.right = tk.Frame(paned, padx=10, pady=10)
        self._build_log()
        paned.add(self.right, minsize=400)

        # Load values from the current config.ts (or defaults)
        self.reload_from_project()

    # ============================================================
    # Form
    # ============================================================
    def _build_form(self):
        # Project path row
        proj_frame = tk.LabelFrame(
            self.left, text=" Remotion project ", font=("Arial", 10, "bold"), padx=8, pady=8
        )
        proj_frame.pack(fill=tk.X, pady=(0, 10))
        tk.Label(proj_frame, text="Path to news-remotion folder:", anchor="w").pack(anchor="w")
        row = tk.Frame(proj_frame)
        row.pack(fill=tk.X, pady=(4, 0))
        tk.Entry(row, textvariable=self.project_path, font=("Arial", 10)).pack(
            side=tk.LEFT, fill=tk.X, expand=True, padx=(0, 6)
        )
        tk.Button(row, text="Browse…", command=self._browse_project).pack(side=tk.LEFT, padx=(0, 4))
        tk.Button(row, text="Reload", command=self.reload_from_project).pack(side=tk.LEFT)

        # Branding
        brand = tk.LabelFrame(
            self.left, text=" Channel branding ", font=("Arial", 10, "bold"), padx=8, pady=8
        )
        brand.pack(fill=tk.X, pady=(0, 10))
        self._labeled_entry(brand, "Channel name", self.channel_name)
        self._labeled_entry(brand, "Tagline (leave blank to hide)", self.channel_tagline)

        # Background video
        bg = tk.LabelFrame(
            self.left, text=" Background video ", font=("Arial", 10, "bold"), padx=8, pady=8
        )
        bg.pack(fill=tk.X, pady=(0, 10))
        tk.Checkbutton(
            bg,
            text="Use background video during image scenes (off = image fills the frame)",
            variable=self.use_bg_video,
            font=("Arial", 10),
            anchor="w",
        ).pack(anchor="w")

        tk.Label(bg, text="Video file:", anchor="w").pack(anchor="w", pady=(8, 0))
        row = tk.Frame(bg)
        row.pack(fill=tk.X, pady=(2, 0))
        tk.Entry(row, textvariable=self.bg_video_path, font=("Arial", 10)).pack(
            side=tk.LEFT, fill=tk.X, expand=True, padx=(0, 6)
        )
        tk.Button(row, text="Browse…", command=self._browse_bg_video).pack(side=tk.LEFT)
        tk.Label(
            bg,
            text="Browse to a video on disk (will be copied to public/), "
            "or type a filename that's already in public/.",
            fg="#666",
            font=("Arial", 8),
            anchor="w",
        ).pack(anchor="w", pady=(2, 0))

        # Image scale
        tk.Label(bg, text="Image card size (% of frame):", anchor="w").pack(anchor="w", pady=(10, 0))
        scale_row = tk.Frame(bg)
        scale_row.pack(fill=tk.X, pady=(2, 0))
        self.scale_label = tk.Label(scale_row, text="70%", width=6, anchor="w", font=("Arial", 10, "bold"))
        self.scale_label.pack(side=tk.LEFT)
        scale_widget = ttk.Scale(
            scale_row,
            from_=0.60,
            to=0.80,
            orient=tk.HORIZONTAL,
            variable=self.image_scale,
            command=self._on_scale_change,
        )
        scale_widget.pack(side=tk.LEFT, fill=tk.X, expand=True)
        tk.Label(
            bg,
            text="0.70 leaves a 54px gap above subtitles. Above 0.78 the image card collides with them.",
            fg="#666",
            font=("Arial", 8),
            anchor="w",
        ).pack(anchor="w", pady=(2, 0))

        # Colors
        colors = tk.LabelFrame(
            self.left, text=" Color palette ", font=("Arial", 10, "bold"), padx=8, pady=8
        )
        colors.pack(fill=tk.X, pady=(0, 10))

        self._color_row(colors, "accent", "Accent (gold) — banner rule, quote marks, hairlines")
        self._color_row(colors, "cream", "Cream — primary text on dark scenes")
        self._color_row(colors, "dark", "Dark — quote / stat background")
        self._color_row(colors, "paper", "Paper — headline scene background")

        # Apply
        self.apply_btn = tk.Button(
            self.left,
            text="Apply configuration",
            font=("Arial", 14, "bold"),
            bg="#4CAF50",
            fg="white",
            command=self.apply,
        )
        self.apply_btn.pack(fill=tk.X, pady=(8, 0))

    def _labeled_entry(self, parent, label, var):
        tk.Label(parent, text=label, anchor="w", font=("Arial", 10)).pack(anchor="w", pady=(4, 0))
        tk.Entry(parent, textvariable=var, font=("Arial", 11)).pack(fill=tk.X, pady=(2, 0))

    def _color_row(self, parent, key, label):
        row = tk.Frame(parent)
        row.pack(fill=tk.X, pady=4)
        tk.Label(row, text=label, anchor="w", font=("Arial", 10), width=58).pack(side=tk.LEFT)
        swatch = tk.Frame(row, width=32, height=24, bg=self.color_vars[key].get() or "#888")
        swatch.pack(side=tk.LEFT, padx=(0, 6))
        swatch.pack_propagate(False)
        self.color_swatches[key] = swatch
        tk.Entry(row, textvariable=self.color_vars[key], font=("Consolas", 10), width=10).pack(
            side=tk.LEFT, padx=(0, 6)
        )
        tk.Button(row, text="Pick…", command=lambda k=key: self._pick_color(k)).pack(side=tk.LEFT)

    def _build_log(self):
        tk.Label(self.right, text="Log", font=("Arial", 12, "bold")).pack(anchor="w")
        self.log_text = scrolledtext.ScrolledText(
            self.right, wrap=tk.WORD, font=("Consolas", 10), bg="#f4f4f4"
        )
        self.log_text.pack(fill=tk.BOTH, expand=True, pady=(6, 0))

    # ============================================================
    # Actions
    # ============================================================
    def _browse_project(self):
        d = filedialog.askdirectory(initialdir=self.project_path.get() or ".", title="Pick news-remotion folder")
        if d:
            self.project_path.set(d)
            self.reload_from_project()

    def _browse_bg_video(self):
        f = filedialog.askopenfilename(
            filetypes=[("Video files", "*.mp4 *.mov *.webm *.mkv"), ("All files", "*.*")],
            title="Pick a background loop video",
        )
        if f:
            self.bg_video_path.set(f)

    def _on_scale_change(self, _):
        self.scale_label.config(text=f"{int(round(self.image_scale.get() * 100))}%")

    def _pick_color(self, key):
        current = self.color_vars[key].get()
        rgb, hex_str = colorchooser.askcolor(
            initialcolor=current if HEX_RE.match(current) else "#888888",
            title=f"Pick {key} color",
        )
        if hex_str:
            self.color_vars[key].set(hex_str)
            self._refresh_swatch(key)

    def _refresh_swatch(self, key):
        hex_str = self.color_vars[key].get()
        if HEX_RE.match(hex_str):
            self.color_swatches[key].config(bg=hex_str)

    def reload_from_project(self):
        """Read existing config.ts (or fall back to defaults) and populate the form."""
        cfg_path = Path(self.project_path.get()) / "src" / "config.ts"
        cfg = parse_config_ts(cfg_path)
        self.channel_name.set(cfg["channelName"])
        self.channel_tagline.set(cfg["channelTagline"])
        self.use_bg_video.set(cfg["useBackgroundVideo"])
        self.bg_video_path.set(cfg["backgroundVideo"])
        self.image_scale.set(cfg["imageScale"])
        for k, v in cfg["colors"].items():
            self.color_vars[k].set(v)
            self._refresh_swatch(k)
        self._on_scale_change(None)
        self._log(f"Loaded config from {cfg_path}" if cfg_path.exists() else f"No config.ts found at {cfg_path} — using defaults")

    def apply(self):
        """Validate, copy background video if needed, write config.ts."""
        self.apply_btn.config(state=tk.DISABLED, text="Working…", bg="#888")
        self.root.update_idletasks()
        try:
            project = Path(self.project_path.get())
            if not project.exists():
                raise ValueError(f"Project folder does not exist: {project}")

            public = project / "public"
            src = project / "src"
            if not src.exists():
                raise ValueError(f"src/ folder not found in {project} — is this really the Remotion project?")

            # Validate colors
            for k, var in self.color_vars.items():
                val = var.get().strip()
                if not HEX_RE.match(val):
                    raise ValueError(f"Color '{k}' is not a valid 6-digit hex: {val!r} (expected like #c8a464)")

            # Validate scale
            scale = float(self.image_scale.get())
            if not 0.50 <= scale <= 0.85:
                raise ValueError(f"Image scale {scale} is outside reasonable range (0.50–0.85)")

            # Handle background video: if absolute path was given, copy to public/
            bg_input = self.bg_video_path.get().strip()
            bg_filename = bg_input  # default: assume it's already a filename in public/
            if bg_input:
                p = Path(bg_input)
                if p.is_absolute():
                    if not p.exists():
                        raise ValueError(f"Background video not found: {p}")
                    public.mkdir(parents=True, exist_ok=True)
                    target = public / p.name
                    if p.resolve() != target.resolve():
                        shutil.copy(p, target)
                        self._log(f"Copied {p.name} → {target}")
                    bg_filename = p.name
                else:
                    # Filename only — verify it's already in public/
                    if self.use_bg_video.get() and not (public / bg_input).exists():
                        self._log(f"⚠️ Warning: {public / bg_input} does not exist — Remotion will error until you put the file there.")

            # Build config dict and write
            cfg = {
                "channelName": self.channel_name.get().strip(),
                "channelTagline": self.channel_tagline.get().strip(),
                "useBackgroundVideo": bool(self.use_bg_video.get()),
                "backgroundVideo": bg_filename or "background.mp4",
                "imageScale": scale,
                "colors": {k: v.get().strip() for k, v in self.color_vars.items()},
            }
            cfg_path = src / "config.ts"
            write_config_ts(cfg_path, cfg)
            self._log(f"✅ Wrote {cfg_path}")
            self._log(
                f"   Branding : {cfg['channelName']}"
                + (f"  •  {cfg['channelTagline']}" if cfg['channelTagline'] else "")
            )
            self._log(f"   Image    : {int(cfg['imageScale']*100)}% size, bg video = {cfg['useBackgroundVideo']}")
            self._log(f"   Colors   : accent={cfg['colors']['accent']}  cream={cfg['colors']['cream']}  dark={cfg['colors']['dark']}  paper={cfg['colors']['paper']}")
            self._log("   → Restart Remotion Studio (or it'll pick up on next render).")
            self._log("")
        except Exception as e:
            self._log(f"❌ {e}")
            messagebox.showerror("Apply failed", str(e))
        finally:
            self.apply_btn.config(state=tk.NORMAL, text="Apply configuration", bg="#4CAF50")

    def _log(self, msg):
        self.log_text.insert(tk.END, msg + "\n")
        self.log_text.see(tk.END)


if __name__ == "__main__":
    root = tk.Tk()
    app = ConfigGUI(root)
    root.mainloop()
