"""
render_bulk.py — Batch-render multiple news-remotion videos.

Each video lives in its own folder under --videos. The script iterates,
configures the Remotion project for that video, runs the render, and saves
the output as <folder-name>.mp4.

Folder layout per video:
  videos/
    video_001/
      avatar.mp4           (required)
      scenes.json          (required — from align_transcript)
      images/              (required — from news_images)
        scene_001.jpg
        ...
      background.mp4       (optional — falls back to whatever's already in public/)
      config.json          (optional — per-video branding overrides)

Per-video config.json fields (all optional, defaults from the script):
  {
    "channelName": "Uncover Truth",
    "channelTagline": "Daily Briefing News",
    "useBackgroundVideo": true,
    "imageScale": 0.70,
    "colors": {
      "accent": "#c8a464", "cream": "#f4f1e8",
      "dark": "#0a0a0c",   "paper": "#f5f1e8"
    }
  }

Usage:
  # Local (slow, no setup needed)
  python render_bulk.py

  # Custom paths
  python render_bulk.py --videos D:\\news\\my-videos --output D:\\news\\done

  # Render only specific folders
  python render_bulk.py --only video_001 video_005

  # Lambda mode (fast, requires one-time AWS setup)
  python render_bulk.py --mode lambda --site news-video
"""

import argparse
import json
import shutil
import subprocess
import sys
import time
from pathlib import Path


# ============================================================
# Default config (used when a video folder has no config.json)
# ============================================================
DEFAULT_CONFIG = {
    "channelName": "The News Report",
    "channelTagline": "Daily Briefing",
    "useBackgroundVideo": True,
    "backgroundVideo": "background.mp4",
    "imageScale": 0.70,
    "colors": {
        "accent": "#c8a464",
        "cream": "#f4f1e8",
        "dark": "#0a0a0c",
        "paper": "#f5f1e8",
    },
}

CONFIG_TS_TEMPLATE = """\
/**
 * News Remotion configuration.
 * Auto-generated by render_bulk.py — overwritten on every render.
 */
export const CONFIG = {{
  channelName: "{channelName}",
  channelTagline: "{channelTagline}",
  useBackgroundVideo: {useBackgroundVideo},
  backgroundVideo: "{backgroundVideo}",
  imageScale: {imageScale:.2f},
  colors: {{
    accent: "{accent}",
    cream: "{cream}",
    dark: "{dark}",
    paper: "{paper}",
  }},
}};

export type AppConfig = typeof CONFIG;
"""


# ============================================================
# Config + asset staging
# ============================================================
def merge_config(user_overrides: dict) -> dict:
    """Merge per-video overrides with defaults (deep merge for 'colors')."""
    result = dict(DEFAULT_CONFIG)
    result["colors"] = dict(DEFAULT_CONFIG["colors"])
    for k, v in (user_overrides or {}).items():
        if k == "colors" and isinstance(v, dict):
            result["colors"].update(v)
        else:
            result[k] = v
    return result


def write_config_ts(project_path: Path, cfg: dict) -> None:
    payload = {
        "channelName": cfg["channelName"].replace('"', '\\"'),
        "channelTagline": cfg["channelTagline"].replace('"', '\\"'),
        "useBackgroundVideo": "true" if cfg["useBackgroundVideo"] else "false",
        "backgroundVideo": cfg["backgroundVideo"],
        "imageScale": float(cfg["imageScale"]),
        **cfg["colors"],
    }
    target = project_path / "src" / "config.ts"
    target.write_text(CONFIG_TS_TEMPLATE.format(**payload), encoding="utf-8")


def stage_assets(project_path: Path, video_folder: Path) -> None:
    """Copy avatar.mp4, scenes.json, images/, background.mp4 into public/."""
    public = project_path / "public"
    public.mkdir(parents=True, exist_ok=True)

    avatar_src = video_folder / "avatar.mp4"
    if not avatar_src.exists():
        raise FileNotFoundError(f"avatar.mp4 not found in {video_folder}")
    shutil.copy(avatar_src, public / "avatar.mp4")

    scenes_src = video_folder / "scenes.json"
    if not scenes_src.exists():
        raise FileNotFoundError(f"scenes.json not found in {video_folder}")
    shutil.copy(scenes_src, public / "scenes.json")

    # Replace images/ atomically — remove old then copy new.
    images_src = video_folder / "images"
    if images_src.exists():
        images_dst = public / "images"
        if images_dst.exists():
            shutil.rmtree(images_dst)
        shutil.copytree(images_src, images_dst)

    # Background video — only copy if provided per-video (otherwise re-use whatever's in public/).
    bg_src = video_folder / "background.mp4"
    if bg_src.exists():
        shutil.copy(bg_src, public / "background.mp4")


# ============================================================
# Render commands
# ============================================================
def run_cmd(cmd: list, cwd: Path) -> None:
    """Run a subprocess and stream its output to our stdout."""
    use_shell = sys.platform == "win32"
    subprocess.check_call(cmd, cwd=str(cwd), shell=use_shell)


def render_local(project_path: Path, output_path: Path, composition: str) -> None:
    run_cmd(
        ["npx", "remotion", "render", composition, str(output_path)],
        cwd=project_path,
    )


def render_lambda(project_path: Path, output_path: Path, composition: str, site_name: str) -> None:
    # Re-deploy the site so the latest staged assets are uploaded to S3.
    # `sites create` is idempotent — overwrites the named site.
    run_cmd(
        ["npx", "remotion", "lambda", "sites", "create", f"--site-name={site_name}"],
        cwd=project_path,
    )
    run_cmd(
        ["npx", "remotion", "lambda", "render", site_name, composition, str(output_path)],
        cwd=project_path,
    )


# ============================================================
# Main loop
# ============================================================
def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--project", default="./news-remotion",
                        help="Path to Remotion project (default: ./news-remotion)")
    parser.add_argument("--videos", default="./videos",
                        help="Directory containing video folders (default: ./videos)")
    parser.add_argument("--output", default="./output",
                        help="Where to save rendered MP4s (default: ./output)")
    parser.add_argument("--mode", choices=["local", "lambda"], default="local",
                        help="Render mode (default: local). Lambda requires AWS setup first.")
    parser.add_argument("--site", default="news-video",
                        help="Lambda site name (default: news-video). Only used in --mode lambda.")
    parser.add_argument("--only", nargs="+", default=None,
                        help="Render only these folder names (default: all)")
    parser.add_argument("--composition", default="NewsVideo",
                        help="Remotion composition ID (default: NewsVideo)")
    parser.add_argument("--skip-existing", action="store_true",
                        help="Skip folders whose output MP4 already exists")
    args = parser.parse_args()

    project_path = Path(args.project).resolve()
    videos_dir = Path(args.videos).resolve()
    output_dir = Path(args.output).resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    if not project_path.exists():
        print(f"❌ Project path not found: {project_path}")
        sys.exit(1)
    if not (project_path / "src").exists():
        print(f"❌ Not a Remotion project (no src/ folder): {project_path}")
        sys.exit(1)
    if not videos_dir.exists():
        print(f"❌ Videos folder not found: {videos_dir}")
        sys.exit(1)

    folders = sorted([f for f in videos_dir.iterdir() if f.is_dir()])
    if args.only:
        wanted = set(args.only)
        folders = [f for f in folders if f.name in wanted]

    if not folders:
        print(f"❌ No video folders found in {videos_dir}")
        sys.exit(1)

    print(f"📋 Found {len(folders)} video(s) to render")
    print(f"   Project : {project_path}")
    print(f"   Mode    : {args.mode}" + (f"  (site: {args.site})" if args.mode == "lambda" else ""))
    print(f"   Output  : {output_dir}")
    print()

    started = time.time()
    failed = []
    skipped = []

    for i, folder in enumerate(folders, 1):
        print("━" * 64)
        print(f"📹 [{i}/{len(folders)}] {folder.name}")
        print("━" * 64)

        output_path = output_dir / f"{folder.name}.mp4"
        if args.skip_existing and output_path.exists():
            print(f"  ⏭️  Skipping — {output_path.name} already exists")
            skipped.append(folder.name)
            continue

        try:
            cfg_path = folder / "config.json"
            user_overrides = {}
            if cfg_path.exists():
                user_overrides = json.loads(cfg_path.read_text(encoding="utf-8"))
                print(f"  📝 Loaded {cfg_path.name}")
            else:
                print(f"  📝 No config.json in {folder.name} — using defaults")
            cfg = merge_config(user_overrides)

            write_config_ts(project_path, cfg)
            stage_assets(project_path, folder)
            print(f"  ✓  Wrote config.ts, staged avatar / scenes / images / background")

            print(f"  ⏳ Rendering → {output_path.name}")
            t0 = time.time()
            if args.mode == "local":
                render_local(project_path, output_path, args.composition)
            else:
                render_lambda(project_path, output_path, args.composition, args.site)
            elapsed = time.time() - t0
            print(f"  ✅ Done in {elapsed / 60:.1f} min")

        except subprocess.CalledProcessError as e:
            print(f"  ❌ Render failed (exit code {e.returncode})")
            failed.append(folder.name)
        except Exception as e:
            print(f"  ❌ {type(e).__name__}: {e}")
            failed.append(folder.name)

    total = time.time() - started
    print()
    print("━" * 64)
    print(f"📊 Batch complete in {total / 60:.1f} min")
    print(f"   Succeeded : {len(folders) - len(failed) - len(skipped)} / {len(folders)}")
    if skipped:
        print(f"   Skipped   : {len(skipped)}  →  {', '.join(skipped)}")
    if failed:
        print(f"   Failed    : {len(failed)}  →  {', '.join(failed)}")
    print("━" * 64)


if __name__ == "__main__":
    main()
