/**
 * News Remotion configuration.
 *
 * Auto-generated by config_gui.py. Edit values via the GUI, or directly
 * here — but be aware the GUI overwrites this file on its next "Apply".
 */
export const CONFIG = {
  // -------- Channel branding (top-left during image scenes) --------
  channelName: "Patricia Hayes",
  channelTagline: "Daily Briefing",

  // -------- Background video (image scenes only) --------
  useBackgroundVideo: true,
  backgroundVideo: "background.mp4",

  // How much of the 1920x1080 frame the news image card occupies.
  // Safe range: 0.65 to 0.78.
  imageScale: 0.70,

  // -------- Color palette --------
  colors: {
    accent: "#ff2d2d",
    cream: "#f4f1e8",
    dark: "#0a0a0c",
    paper: "#f5f1e8",
  },
};

export type AppConfig = typeof CONFIG;
